import {
  faPenToSquare,
  faPlus,
  faTrashCan,
  faFilter,
  faMagnifyingGlass,
  faUserPlus,
  faUserInjured,
  faUserDoctor,
  faClipboard,
  faHome,
  faChevronRight,
  faCircleExclamation,
  faBars,
  faDatabase,
  faPerson,
  faPercent,
  faHospital,
  faHandHoldingDollar,
  faHandsHoldingChild,
  faUsers,
  faHand,
  faCalendar,
  faCalendarPlus,
  faEllipsis,
  faCheck,
  faXmark,
  faRightFromBracket,
  faChevronLeft,
  faCalendarMinus,
  faChevronDown,
  faFolderOpen,
  faDollarSign,
  faCircleDollarToSlot,
  faGear,
  faCircleCheck,
  faCircleXmark,
  faTable,
  faCubes,
  faFileInvoiceDollar,
  faCloudArrowDown,
  faGauge,
  faPaperPlane,
  faInfo,
  faExclamation,
  faCoins,
  faRotateLeft,
  faRotateRight,
  faUserGroup,
  faTableList,
  faTableCells,
  faCopy,
  faPaste,
  faMagnifyingGlassDollar,
  faHotel,
  faHouseFlag,
  faCity,
  faShop,
  faMapLocationDot,
} from '@fortawesome/free-solid-svg-icons';

export const ICONS = {
  pen: faPenToSquare,
  plus: faPlus,
  trash: faTrashCan,
  filter: faFilter,
  search: faMagnifyingGlass,
  newUser: faUserPlus,
  paciente: faUserInjured,
  doctor: faUserDoctor,
  reports: faClipboard,
  home: faHome,
  arrowR: faChevronRight,
  arrowL: faChevronLeft,
  arrowD: faChevronDown,
  alert: faCircleExclamation,
  menu: faBars,
  datos: faDatabase,
  grupos: faPerson,
  grupoEspecifico: faHand,
  descuentos: faPercent,
  hospital: faHospital,
  aseguradora: faHandHoldingDollar,
  bloque: faCubes,
  servicios: faHandsHoldingChild,
  personal: faUsers,
  calendar: faCalendar,
  calendarPlus: faCalendarPlus,
  dots: faEllipsis,
  check: faCheck,
  xmark: faXmark,
  logout: faRightFromBracket,
  calendarX: faCalendarMinus,
  folder: faFolderOpen,
  dollarSing: faDollarSign,
  billete: faCircleDollarToSlot,
  settings: faGear,
  circleCheck: faCircleCheck,
  powerOff: faCircleXmark,
  excel: faTable,
  history: faFileInvoiceDollar,
  descarga: faCloudArrowDown,
  dashboard: faGauge,
  send: faPaperPlane,
  info: faInfo,
  exclamation: faExclamation,
  coins: faCoins,
  rotateLeft: faRotateLeft,
  rotateRight: faRotateRight,
  userGroup: faUserGroup,
  tableList: faTableList,
  tableCells: faTableCells,
  copy: faCopy,
  paste: faPaste,
  magnifyingGlassDollar: faMagnifyingGlassDollar,
  hotel: faHotel,
  faHouseFlag,
  faCity,
  faShop,
  faMapLocationDot
};